services:
  authentication:
    container_name: authentication
    build:
      context: AuthenticationService/
      dockerfile: Dockerfile
    ports:
      - published: ${AUTH_PORT:-3000}
        target: 3000
    environment:
      JWT_SECRET: ${JWT_SECRET}
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "${MOVIES_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${MOVIES_DB_DATABASE}
      POSTGRES_USER: ${MOVIES_DB_USERNAME}
      POSTGRES_PASSWORD: ${MOVIES_DB_PASSWORD} 
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
  movies:
    build: MoviesService/
    container_name: movies
    restart: always
    ports:
      - "${MOVIES_PORT}:${MOVIES_PORT}"
    environment:
      MOVIES_PORT: ${MOVIES_PORT}
      MOVIES_DB_HOST: db
      MOVIES_DB_DATABASE: ${MOVIES_DB_DATABASE}
      MOVIES_DB_USERNAME: ${MOVIES_DB_USERNAME}
      MOVIES_DB_PASSWORD: ${MOVIES_DB_PASSWORD} 
      MOVIES_DB_PORT: ${MOVIES_DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db


# volumes:
#     postgres-data: