name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: upping serivces
        run: |
          docker-compose up --build -d db
          docker-compose up --build -d authentication
      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: "10s"
      - name: Check running containers
        run: docker ps -a
      - run: npm install
      - name: migration
        run: npm run typeorm migration:run
      - run: npm test
